export const GET_ALL_PENDING = 'GET_ALL_PENDING';
export const GET_ALL_SUCCESS = 'GET_ALL_SUCCESS';
export const GET_ALL_FAILURE = 'GET_ALL_FAILURE';

export const ADD_EMPLOYEE_PENDING = 'ADD_EMPLOYEE_PENDING';
export const ADD_EMPLOYEE_SUCCESS = 'ADD_EMPLOYEE_SUCCESS';
export const ADD_EMPLOYEE_FAILURE = 'ADD_EMPLOYEE_FAILURE';

export const EDIT_EMPLOYEE_PENDING = 'EDIT_EMPLOYEE_PENDING';
export const EDIT_EMPLOYEE_SUCCESS = 'EDIT_EMPLOYEE_SUCCESS';
export const EDIT_EMPLOYEE_FAILURE = 'EDIT_EMPLOYEE_FAILURE';

export const REMOVE_EMPLOYEE_PENDING = 'REMOVE_EMPLOYEE_PENDING';
export const REMOVE_EMPLOYEE_SUCCESS = 'REMOVE_EMPLOYEE_SUCCESS';
export const REMOVE_EMPLOYEE_FAILURE = 'REMOVE_EMPLOYEE_FAILURE';